{{- $root := . -}}
{{- $fullName := include "stoatchat.fullname" . -}}
{{- range $instance := .Values.global.livekit }}
{{- if and $instance.name (not $instance.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-livekit-{{ $instance.name }}-keys"
  namespace: {{ $root.Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" $root | nindent 4 }}
type: Opaque
stringData:
  keys.yaml: |
    {{ $instance.name }}: {{ $instance.secret }}
{{- end }}
{{- end }}
