{{- $root := . -}}
{{- $fullName := include "stoatchat.fullname" . -}}
{{- range $instance := .Values.global.livekit }}
{{- if $instance.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-livekit-{{ $instance.name }}-secret"
  namespace: {{ $root.Values.global.namespace }}
  labels:
    {{- include "stoatchat.labels" $root | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    port: 7880
    redis:
        {{- if $root.Values.global.subcharts.redis.connection_url }}
        {{- $redisUrl := $root.Values.global.subcharts.redis.connection_url }}
        {{- $redisUserInfo := trimPrefix "redis://" $redisUrl | regexFind "[^@]+" }}
        address: {{ regexFind "[^/]+" (index (splitList "@" $redisUrl) 1) }}
        username: {{ regexFind "[^:/]+" $redisUserInfo | quote }}
        password: {{ last (regexFindAll ":[^@]+" $redisUserInfo -1) | trimPrefix ":" | quote }}
        {{- else }}
        address: "{{ $fullName }}-redis-master:6379"
        {{- end }}
    webhook:
      api_key: {{ $instance.name }}
      urls:
        - 'http://{{ $fullName }}-voice-ingress:8500/{{ $instance.name }}'
    logging:
      level: debug
    key_file: /etc/livekit-keys/keys.yaml
  {{- if not $instance.existingSecret }}
  keys.yaml: |
    {{ $instance.name }}: {{ $instance.secret }}
  {{- end }}
{{- end }}
{{- end }}
